### ISSUE TITLE
Failed to login from npm cli

### ISSUE THREAD

**Issue by leominov** [Alexandre-io/verdaccio-ldap#62]
Packages:

- verdaccio@4.2.0
- verdaccio-profile-api@0.2.4
- verdaccio-ldap@4.0.0

Config:

```
storage: /storage

plugins: /verdaccio/plugins
web:
  title: Advert Verdaccio

auth:
  ldap:
    type: ldap
    cache:
      size: 100
      expire: 300
    client_options:
      url: 'ldap://***'
      adminDn: 'CN=gitlab_ad,OU=management_accounts_ou,OU=IT,DC=***,DC=ru'
      adminPassword: '***'
      searchBase: 'DC=***,DC=ru'
      searchFilter: '(samaccountname={{username}})'
      tlsOptions:
        rejectUnauthorized: False

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

max_body_size: 50mb

middlewares:
  profile-api:
  audit:
    enabled: true

logs:
  - {type: stdout, format: pretty, level: trace}
```

Login via UI works fine, here is some logs:

```
 info <-- 172.17.0.1 requested 'POST /-/verdaccio/login'
 trace--- authenticating l.aminov
 trace--- user cache miss: key="l.aminov"
 trace--- ldap authenticate: bind: CN=gitlab_ad,OU=management_accounts_ou,OU=IT,DC=***,DC=ru
 debug--- connected after 1 attempt(s)
 debug--- connected after 1 attempt(s)
...
```

But from cli I got this:

```
npm login --registry http://0.0.0.0:4873
Username: (l.aminov) 
Password: (<default hidden>) 
Email: (this IS public) (l.aminov@***) 
Logged in as l.aminov on http://0.0.0.0:4873/.
```

And this error in server logs:

```
 info <-- 172.17.0.1 requested 'PUT /-/user/org.couchdb.user:l.aminov'
 trace--- add user l.aminov
 trace--- the user l.aminov could not being added. Error: { message: 'bad username/password, access denied',
  name: 'ConflictError',
  stack:
   'ConflictError: bad username/password, access denied\n    at getError (/usr/local/share/.config/yarn/global/node_modules/@verdaccio/commons-api/lib/index.js:111:45)\n    at Object.getConflict (/usr/local/share/.config/yarn/global/node_modules/@verdaccio/commons-api/lib/index.js:117:10)\n    at Object.add_user (/usr/local/share/.config/yarn/global/node_modules/verdaccio/build/lib/auth-utils.js:109:34)\n    at next (/usr/local/share/.config/yarn/global/node_modules/verdaccio/build/lib/auth.js:171:23)\n    at next (/usr/local/share/.config/yarn/global/node_modules/verdaccio/build/lib/auth.js:168:9)\n    at Auth.add_user (/usr/local/share/.config/yarn/global/node_modules/verdaccio/build/lib/auth.js:190:7)\n    at /usr/local/share/.config/yarn/global/node_modules/verdaccio/build/api/endpoint/api/user.js:61:12\n    at Layer.handle [as handle_request] (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:281:22\n    at param (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:354:14)\n    at param (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:365:14)\n    at param (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:365:14)\n    at paramCallback (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:401:21)',
  code: 409,
  signal: undefined }
 http <-- 409, user: null(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:l.aminov', error: bad username/password, access denied
```

There is no LDAP opening connections or something other. What I'm doing wrong?

**Comment by leominov** [comment]
Looks like adding `htpasswd` auth backend solve this problem.
